services:
  mongodb:
    image: mongo:latest
    container_name: smart-kot-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - kot-network

  backend:
    image: navenkumar68/smart-kot-backend:latest
    container_name: smart-kot-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - kot-network

  frontend:
    image: navenkumar68/smart-kot-frontend:latest
    container_name: smart-kot-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - kot-network

networks:
  kot-network:
    driver: bridge

volumes:
  mongo_data:
