apiVersion: apps/v1
kind: Deployment
metadata:
  name: kot-backend
  labels:
    app: kot-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kot-backend
  template:
    metadata:
      labels:
        app: kot-backend
    spec:
      containers:
      - name: backend
        image: navenkumar68/smart-kot-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: kot-backend-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
